import type { editor } from "monaco-editor";

export const ZUUP_THEME = "zuup-dark";

export const ZUUP_THEME_DATA: editor.IStandaloneThemeData = {
  base: "vs-dark",
  inherit: true,
  rules: [
    { token: "comment", foreground: "5c6370", fontStyle: "italic" },
    { token: "keyword", foreground: "e63462" },
    { token: "string", foreground: "98c379" },
    { token: "number", foreground: "d19a66" },
    { token: "type", foreground: "61afef" },
    { token: "function", foreground: "61afef" },
    { token: "variable", foreground: "e06c75" },
    { token: "operator", foreground: "56b6c2" },
    { token: "delimiter", foreground: "abb2bf" },
    { token: "tag", foreground: "e63462" },
    { token: "attribute.name", foreground: "d19a66" },
    { token: "attribute.value", foreground: "98c379" },
  ],
  colors: {
    "editor.background": "#0d0f17",
    "editor.foreground": "#cdd6e4",
    "editor.lineHighlightBackground": "#1a1d2e",
    "editor.selectionBackground": "#e6346233",
    "editor.inactiveSelectionBackground": "#e6346218",
    "editorCursor.foreground": "#e63462",
    "editorLineNumber.foreground": "#3a3f54",
    "editorLineNumber.activeForeground": "#e63462",
    "editorIndentGuide.background": "#1e2133",
    "editorIndentGuide.activeBackground": "#2e3250",
    "editor.selectionHighlightBackground": "#e6346215",
    "editorBracketMatch.background": "#e6346225",
    "editorBracketMatch.border": "#e6346250",
    "editorSuggestWidget.background": "#141724",
    "editorSuggestWidget.border": "#1e2133",
    "editorSuggestWidget.selectedBackground": "#e6346230",
    "editorSuggestWidget.highlightForeground": "#e63462",
    "editorWidget.background": "#141724",
    "editorWidget.border": "#1e2133",
    "editorGhostText.foreground": "#cdd6e45c",
    "editorGhostText.background": "#00000000",
    "scrollbarSlider.background": "#2a2e42",
    "scrollbarSlider.hoverBackground": "#3a3f54",
    "scrollbarSlider.activeBackground": "#e6346250",
  },
};
